name: CI/CD - Run Tests and Vercel Dev Deployment

env:
  NEXT_PUBLIC_API_BASE_URL: 'https://devstore-next-api-red.vercel.app'
  APP_URL: 'http://localhost:3000'

on:
  push:
    branches:
      - dev

jobs:
  run-e2e-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start

  vercel-dev-deploy:
    runs-on: ubuntu-latest
    needs: run-e2e-tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build

      - name: Vercel Dev Deployment
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          github-comment: false
          alias-domains: |
            dev-sneaker-store.vercel.app
